export const GET_QUOTES = 'GET_QUOTES';
export const SET_START_QUOTES = 'SET_START_QUOTES';
export const FETCH_QUOTES_FAILED = 'FETCH_QUOTES_FAILED';

export const SET_AUTHORIZATION = 'SET_AUTHORIZATION';
export const AUTHORIZATION_SUCCES = 'AUTHORIZATION_SUCCES';
export const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED';
export const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR';

export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';

export const PARTNER_INFO_SUCCESS = 'PARTNER_INFO_SUCCESS';
export const PARTNER_INFO_FAIL = 'PARTNER_INFO_FAIL';
export const SET_PARTNER_INFO = 'SET_PARTNER_INFO';
export const SINGLE_PARTNER_INFO_SUCCESS = 'SINGLE_PARTNER_INFO_SUCCESS';
export const SINGLE_PARTNER_INFO_FAIL = 'SINGLE_PARTNER_INFO_FAIL';
export const SET_SINGLE_PARTNER_INFO = 'SET_SINGLE_PARTNER_INFO';

export const BORROW_INFO_SUCCESS = 'PARTNER_INFO_SUCCESS';
export const BORROW_INFO_FAIL = 'PARTNER_INFO_FAIL';
export const SET_BORROW_INFO = 'SET_PARTNER_INFO';