export const GET_QUOTES = 'GET_QUOTES';
export const SET_START_QUOTES = 'SET_START_QUOTES';
export const FETCH_QUOTES_FAILED = 'FETCH_QUOTES_FAILED';

export const SET_AUTHORIZATION = 'SET_AUTHORIZATION';
export const AUTHORIZATION_SUCCES = 'AUTHORIZATION_SUCCES';
export const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED';
export const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR';

export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';

export const GET_USER_WHOLE_INFO_SUCCESS = 'GET_USER_WHOLE_INFO_SUCCESS';
export const GET_USER_WHOLE_INFO_FAIL = 'GET_USER_WHOLE_INFO_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const PARTNER_INFO_SUCCESS = 'PARTNER_INFO_SUCCESS';
export const PARTNER_INFO_FAIL = 'PARTNER_INFO_FAIL';
export const SET_PARTNER_INFO = 'SET_PARTNER_INFO';
export const SINGLE_PARTNER_INFO_SUCCESS = 'SINGLE_PARTNER_INFO_SUCCESS';
export const SINGLE_PARTNER_INFO_FAIL = 'SINGLE_PARTNER_INFO_FAIL';
export const SET_SINGLE_PARTNER_INFO = 'SET_SINGLE_PARTNER_INFO';

export const BORROW_INFO_SUCCESS = 'BORROW_INFO_SUCCESS';
export const BORROW_INFO_FAIL = 'BORROW_INFO_FAIL';
export const SET_BORROW_INFO = 'SET_BORROW_INFO';
export const BORROW_SUM_SUCCESS = 'BORROW_SUM_SUCCESS';
export const BORROW_SUM_FAIL = 'BORROW_SUM_FAIL';

export const LOAN_INFO_SUCCESS = 'LOAN_INFO_SUCCESS';
export const LOAN_INFO_FAIL = 'LOAN_INFO_FAIL';
export const SET_LOAN_INFO = 'SET_LOAN_INFO';
export const LOAN_SUM_SUCCESS = 'LOAN_SUM_SUCCESS';
export const LOAN_SUM_FAIL = 'LOAN_SUM_FAIL';

export const BORROW_PAYMENT_INFO_SUCCESS = 'BORROW_PAYMENT_INFO_SUCCESS';
export const BORROW_PAYMENT_INFO_FAIL = 'BORROW_PAYMENT_INFO_FAIL';
export const BORROW_PAYMENT_GET_INFO = 'BORROW_PAYMENT_GET_INFO';
export const BORROW_PAYMENT_SUM_SUCCESS = 'BORROW_PAYMENT_SUM_SUCCESS';
export const BORROW_PAYMENT_SUM_FAIL = 'BORROW_PAYMENT_SUM_FAIL';
export const BORROW_PAYMENT_GET_SUM = 'BORROW_PAYMENT_GET_SUM';

export const LOAN_PAYMENT_INFO_SUCCESS = 'LOAN_PAYMENT_INFO_SUCCESS';
export const LOAN_PAYMENT_INFO_FAIL = 'LOAN_PAYMENT_INFO_FAIL';
export const LOAN_PAYMENT_GET_INFO = 'LOAN_PAYMENT_GET_INFO';
export const LOAN_PAYMENT_SUM_SUCCESS = 'LOAN_PAYMENT_SUM_SUCCESS';
export const LOAN_PAYMENT_SUM_FAIL = 'LOAN_PAYMENT_SUM_FAIL';
export const LOAN_PAYMENT_GET_SUM = 'LOAN_PAYMENT_GET_SUM';