export const GET_QUOTES = 'GET_QUOTES';
export const SET_START_QUOTES = 'SET_START_QUOTES';
export const FETCH_QUOTES_FAILED = 'FETCH_QUOTES_FAILED';

export const SET_AUTHORIZATION = 'SET_AUTHORIZATION';
export const AUTHORIZATION_SUCCES = 'AUTHORIZATION_SUCCES';
export const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED';
export const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR';

export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';